### ISSUE TITLE
"submit content" button

### ISSUE THREAD

**Issue by JulianNorton** [JulianNorton/web_design#26]
submit content button all kinds of messed up
![screen shot 2015-01-14 at 1 37 46 pm](https://cloud.githubusercontent.com/assets/2412992/5744891/91b64760-9bf2-11e4-8d3a-37f4c34ac787.png)

**Comment by purduekenny** [comment]
i think that's the "floating" one that pops up and follows you? no?

either way, looks terrible. :D

**Comment by JulianNorton** [comment]
kill it
