### ISSUE TITLE
FAQ Banner Spacing

### ISSUE THREAD

**Issue by CameronGraham** [JulianNorton/web_design#35]
"Did you know we had a FAQ?" banner covering part of post.
![capture](https://cloud.githubusercontent.com/assets/3112138/9385590/27f126e8-474f-11e5-9e6c-ac937fd88207.PNG)

**Comment by JulianNorton** [comment]
@purduekenny can you confirm the fix? I don't see anything in the commit history.

**Comment by JulianNorton** [comment]
resolved
