### ISSUE TITLE
Give Gold popup is terribly broken

### ISSUE THREAD

**Issue by purduekenny** [JulianNorton/web_design#45]
![image](https://cloud.githubusercontent.com/assets/1843220/15323091/3d180d40-1c0e-11e6-9f20-b6e9d36ec426.png)

Chrome Version 50.0.2661.102 m (64-bit) Windows 7

**Comment by JulianNorton** [comment]
For context, here it is with styles off:
![screen shot 2016-05-17 at 9 57 46 am](https://cloud.githubusercontent.com/assets/2412992/15324782/d2869c14-1c15-11e6-894d-e431c5af0651.png)

the close 'x' is a little weird, but it seems jankey by design.

**Comment by dominicgan** [comment]
These button styles from the theme are clashing with the close 'x'
![Button styles](http://i.imgur.com/WS6Cxhf.png)

Adding this to the gold button css fixes it:

    .gold-payment .close-button {
        box-shadow: none;
        padding: 0;
    }

**Comment by brianmjerome** [comment]
I will add a pull request to assist with the issues regarding this element. I've attached a file of what the css changes would appear as:
<img width="690" alt="" src="https://cloud.githubusercontent.com/assets/1984528/19450978/85e546c6-9479-11e6-86cc-04ab02c0fee7.png">

There is a commented line that can remove the laurel from the background if desired.
