### ISSUE TITLE
Submission Area: Night mode issue

### ISSUE THREAD

**Issue by purduekenny** [JulianNorton/web_design#47]
@iPlain take a gander at this issue @ https://www.reddit.com/r/web_design/submit?selftext=true 
There's no sidebar for your check. Not sure how you want to fix this.

![image](https://cloud.githubusercontent.com/assets/1843220/15323227/078c7372-1c0f-11e6-8540-0a3748906b37.png)

**Comment by iPlain** [comment]
Fixed with latest PR

**Comment by JulianNorton** [comment]
resolved with merge
